---
title: "Energy from AGB"
author: "JP"
date: "`r Sys.Date()`"
output: html_document
---

Protein that grazing livestock can derive from AGB was calculated in script 5_protein_from_AGB.Rmd.
That script should be run first and then we convert that amount of protein to kcals in this script.

# Convert protein production to kcal


```{r}

# how one_kg_prot_to_kcal varies by counrty
fbs_animals_wide_filled %>%
    filter(Item == "Meat") %>%
    pull(one_kg_prot_to_kcal) |> 
  hist(main = "one_kg_prot_to_kcal by country", breaks = 20) # around 10 000, not much dispersion

fbs_animals_wide_filled %>%
    filter(Item == "Bovine Meat") %>%
    pull(one_kg_prot_to_kcal) |> 
  hist(main = "one_kg_prot_to_kcal by country", breaks = 20) # more dispersion

# kcal production raster, example with dairy cows
# faoid_and_kcals_dairy  <- 
#   fbs_animals_wide_filled %>%
#   filter(Item == "Bovine Meat") %>%
#   dplyr::select(Area.Code, one_kg_prot_to_kcal)
# 
# ## create reclassification matrix
# rcl_mat_countries_to_one_kg_prot_to_kcal <-
#   matrix(c(
#     faoid_and_kcals_dairy$Area.Code,
#     faoid_and_kcals_dairy$one_kg_prot_to_kcal),
#     ncol = 2)
# 
# 
# ## create raster where fao id has been replaced with one_kg_prot_to_kcal
# r_one_kg_prot_to_kcal_dairy  <- 
#   cntry_raster %>% 
#   classify(rcl_mat_countries_to_one_kg_prot_to_kcal, 
#            others = 
#              (fbs_animals_wide_filled %>% 
#                 filter(Area == "World", Item == "Bovine Meat") %>%
#                 pull(one_kg_prot_to_kcal)))
#             # use global averages for missing countries
# 
# plot(r_one_kg_prot_to_kcal_dairy, main = "one_kg_prot_to_kcal_dairy by country")
# 
# 
# ## multiply with protein production raster
# plot((r_one_kg_prot_to_kcal_dairy * r_protein_from_AGB_kg_ha$dairy /1e6),
#      main = "Amount of kcal dairy cattle could produce from AGB (MM kcal per ha)")
# 



# ------------------------ the same for different animal species with a function -- calculate per pix!
f_energy_from_protein_MMkcal_perpix <- function(animalcategory_fao) {

  ## get protein fraction for spesific crop species
  faoid_and_one_kg_prot_to_kcal <-
    fbs_animals_wide_filled %>%
    filter(Item == animalcategory_fao) %>%
    dplyr::select(Area.Code, 
                  one_kg_prot_to_kcal) # created elsewhere

  ## reclassification matrix
  rcl_mat_countries_to_one_kg_prot_to_kcal <-
    matrix(c(
      faoid_and_one_kg_prot_to_kcal$Area.Code,
      faoid_and_one_kg_prot_to_kcal$one_kg_prot_to_kcal),
      ncol = 2)

  ## classify. Creates a raster that shows one_kg_to_prot for each country
  r_one_kg_prot_to_kcal  <- 
    cntry_raster %>% 
    classify(rcl_mat_countries_to_one_kg_prot_to_kcal, 
             others = 
               (fbs_animals_wide_filled %>%
                       filter(Area == "World", Item == animalcategory_fao) %>% 
                  pull(one_kg_prot_to_kcal))) # fill empty values with global averages
  
  
  # protein production raster (first chunck)
  r_protein_production_animals <- r_protein_from_AGB_kg_perpix
  

  ## kcal production raster
  r_kcal_MM_perpix <-
    r_protein_production_animals * r_one_kg_prot_to_kcal / 1e6
  names(r_kcal_MM_perpix) <- paste0(animalcategory_fao, "_MMkcal_perpix")

  return(r_kcal_MM_perpix) # MM per pix 
}


f_energy_from_protein_MMkcal_perpix(animalcategory_fao = "Bovine Meat") %>% 
  plot(., main = "Amount of kcal dairy cows could produce from AGB (MM kcal per pixel)")




# Derive energy production raster for all animal species
r_kcal_from_AGB_MM_perpix <- c(

  f_energy_from_protein_MMkcal_perpix(animalcategory_fao = "Bovine Meat"),

  f_energy_from_protein_MMkcal_perpix(animalcategory_fao = "Mutton & Goat Meat") ,

  # add kcal produced by current herd structure
  f_energy_from_protein_MMkcal_perpix(animalcategory_fao = "Meat")  
)

r_kcal_from_AGB_MM_perpix
plot(r_kcal_from_AGB_MM_perpix)

# lets use the mean in calculation
r_kcal_from_AGB_MM_perpix_mean <- mean(r_kcal_from_AGB_MM_perpix, na.rm= T)

writeRaster(r_kcal_from_AGB_MM_perpix_mean, filename =
            here("Data", "Intermediate_input",
                 "r_kcal_from_AGB_MM_perpix_mean.tif"), 
            overwrite = T)

# get the file
r_kcal_from_AGB_MM_perpix_mean <- 
  here("Data", "Intermediate_input",
       "r_kcal_from_AGB_MM_perpix_mean.tif") |> 
  rast()
```


# Global sums

```{r}
# total kcal production
global(r_kcal_from_AGB_MM_perpix_mean*1e6, fun = "sum", na.rm = T)/1e12  # 109 trillion kcal in 2020




# r_kcal_from_AGB_MM_perpix <- 
#   r_kcal_from_AGB_MM_ha * cellSize(r_kcal_from_AGB_MM_ha, unit ="ha") *
#   r_fraction_gl_0toNA
# names(r_kcal_from_AGB_MM_perpix) <- c("dairy_MMkcal_perpix", "beef_MMkcal_perpix",
#                                      "sheep_and_goats_MMkcal_perpix", "current_herd_str_MMkcal_perpix" )
# was dairy 315 beef 69 sheep 105, current herd 153 much earlier in 2020 and with different method



# this in broader context: 
  # energy need adar based on FAO 2358 kcal/capita/d (https://www.fao.org/faostat/en/#data/FS)
# "Average dietary energy requirement (kcal/cap/day"
global(r_kcal_from_AGB_MM_perpix_mean*1e6, fun = "sum", na.rm = T) /
  (2358*365)/1e6 # 128 million people could be fed with livestog grazing

  # how many kcal per capita day grazers produce
# global(r_kcal_from_AGB_MM_perpix_mean*1e6, fun = "sum", na.rm = T)  / # 
#   (1000* foodBalanceSheets_semiraw %>% filter(Area == "World", Item == "Population") %>% pull(Y2020)) / # persons
#   365  # 37 kcal per capita d
# ---  how much this is from the need?
(global(r_kcal_from_AGB_MM_perpix_mean*1e6, fun = "sum", na.rm = T)  / # 
  (1000* foodBalanceSheets_semiraw %>% filter(Area == "World", Item == "Population") %>% pull(Y2020)) / # persons
  365 ) /
  2358 # 2%
```

# Kcal per ha from AGB

```{r}
r_kcal_from_AGB_MM_ha <-
  r_kcal_from_AGB_MM_perpix_mean /
  (cellSize(r_kcal_from_AGB_MM_perpix_mean, unit = "ha") *
     r_fraction_gl_0toNA)

names(r_kcal_from_AGB_MM_ha) <- "MMkcal_per_ha"

writeRaster(r_kcal_from_AGB_MM_ha, filename =
              here("Data", "Intermediate_input",
                   "r_kcal_from_AGB_MM_ha.tif"),
            overwrite = T)

# Get the file
r_kcal_from_AGB_MM_ha <- 
  here("Data", "Intermediate_input","r_kcal_from_AGB_MM_ha.tif") |> 
  rast()


```

