---
title: "Supplementary combined energy"
author: "JP"
date: "`r Sys.Date()`"
output: html_document
---

Run this after 7_combined_protein_and_comparisons.Rmd


# Calculate livestock contribution to total energy

```{r}
r_energy_combined_MM_perpix <-
  classify(r_kcal_from_AGB_MM_perpix_mean, cbind(NA, 0)) +
  classify(r_kcal_allcrops_sum_MM_perpix, cbind(NA, 0))
names(r_energy_combined_MM_perpix) <- "combined_energy"



# Grazing livestock's share of total kcal production on agricultural land OR  share of the total energy that originates from livestock
r_share_of_total_energy_livestock <- 
  100* (classify(r_kcal_from_AGB_MM_perpix_mean, cbind(NA,0)) / 
          r_energy_combined_MM_perpix)
names(r_share_of_total_energy_livestock) <-
  "share_of_total_energy_livestock"

plot(r_share_of_total_energy_livestock, 
     main = "Contribution of livestock to total energy production")


# ------------------------------------------------------ maybe not need to mask them to different areas
# --------------------------------------------------- same masked to cl
# r_share_of_total_energy_livestock_croplandmask <-
#   mask(r_share_of_total_energy_livestock, 
#        r_fraction_cl_0toNA)

#   # 10% of over (of agr land) croplands AND 10% of over (of agr land) grazing lands
# r_share_of_total_energy_livestock_mixed <-
#   mask(r_share_of_total_energy_livestock,
#        r_gl_cl_share_mixed)
# 
# 
# # ----------------------- further masked to areas where SI extremely low (below 10)
# # r_share_of_total_energy_livestock_SIbetween1to10mask <-
# #   mask(r_share_of_total_energy_livestock,
# #        SI_5arcmin_range_1to10)
# 
# SI_5arcmin_range_1to10 <- SI_5arcmin
# SI_5arcmin_range_1to10[SI_5arcmin_range_1to10 >= 10] <- NA
# SI_5arcmin_range_1to10[SI_5arcmin_range_1to10 <= 1] <- NA
# 
# 
# r_share_of_total_energy_livestock_SIbetween1to10mask <-
#   mask(r_share_of_total_energy_livestock, 
#        SI_5arcmin_range_1to10)
# 

# SAVE
# total combined energy
writeRaster(r_energy_combined_MM_perpix,
            here("Data", "Intermediate_input",
                 "r_energy_combined_MM_perpix.tif"),
            overwrite = TRUE)

r_energy_combined_MM_perpix <-
  here("Data", "Intermediate_input",
       "r_energy_combined_MM_perpix.tif") |>
  rast()


writeRaster(r_share_of_total_energy_livestock,
            here("Data", "Intermediate_input",
                 "r_share_of_total_energy_livestock.tif"),
            overwrite = TRUE)

# Get the file
r_share_of_total_energy_livestock <-
  here("Data", "Intermediate_input",
       "r_share_of_total_energy_livestock.tif") |>
  rast()
```

# Results in kg per ha for figures

```{r}

################################################## total combined energy per ha 
r_energy_combined_MM_ha <-
  classify(r_kcal_from_AGB_MM_ha, cbind(NA, 0)) +
  classify(r_kcal_allcrops_sum_MM_ha, cbind(NA, 0))

names(r_energy_combined_MM_ha) <- "combined_energy"


r_energy_combined_MM_ha <-
  mask(r_energy_combined_MM_ha, r_fraction_gl_cl_total_0toNA)

# # -------------------------------------------------------------------- mask
#   # masked to mixed areas
# r_energy_combined_MM_ha_wheremixed <-
#   mask(r_energy_combined_MM_ha, 
#        r_gl_cl_share_mixed)
# 
# 
#   # further masked to cl where SI extremely low (below 10)
# r_energy_combined_MM_ha_SIbetween1to10mask <-
#   mask(r_energy_combined_MM_ha,
#        SI_5arcmin_range_1to10)
# plot(r_energy_combined_MM_ha_SIbetween1to10mask)

# SAVE
writeRaster(r_energy_combined_MM_ha,
            here("Data", "Intermediate_input",
                 "r_energy_combined_MM_ha.tif"),
            overwrite = TRUE)

# Get the file
r_energy_combined_MM_ha <-
  here("Data", "Intermediate_input",
       "r_energy_combined_MM_ha.tif") |>
  rast()


```



# Prepare data for plots -- no need if we dont do masks

```{r}

# r_combined_energy_plots <- c(
#   r_energy_combined_MM_ha,
#   r_energy_combined_MM_ha_wheremixed,
#   r_energy_combined_MM_ha_SIbetween1to10mask)
# names(r_combined_energy_plots) <-
#   c("MMkcal_ha", "MMkcal_ha_mixed", "MMkcal_ha_SI1to10")
# 
# r_shares_plot_energy <- c(
#   r_share_of_total_energy_livestock,
#   r_share_of_total_energy_livestock_mixed,
#   r_share_of_total_energy_livestock_SIbetween1to10mask
#   )
# names(r_shares_plot_energy) <- c(
#   "liv_shre_tot_energy", "liv_shre_tot_energy_mixed", "liv_shre_tot_energy_SI1to10mask")

```


# Global sums

```{r}
global(r_energy_combined_MM_perpix*1e6, "sum", na.rm = T)/1e12 # 10575 trillion, which is the same as reported crops + animals

```
