

# Optimoidut sadot Suomi
- Data luettu globaalille tasolle muissa skripteissä

```{r}
Finland_geom <- adm_10m %>% filter(ADMIN == "Finland") %>% dplyr::select(ADMIN) |> 
  as("Spatial") |>   vect()


SI_30arcsec_fi <- crop_and_mask(SI_30arcsec, Finland_geom)
threshold_fi <- c(0, 1, 33, 90)

r_fraction_gl_cl_total_fi <- crop_and_mask(r_fraction_gl_cl_total, Finland_geom)
names(r_fraction_gl_cl_total_fi) <- "gl_cl_fraction_of_cell"
```



# Chunk 2

```{r}


# Define a function to classify, aggregate, and resample the raster based on a threshold
f_classify_and_aggregate_resample_fi <- function(threshold_fi) {
  rclmat <- matrix(c(threshold_fi, Inf, 1), ncol = 3, byrow = TRUE)
  classified_raster <- classify(SI_30arcsec_fi, rclmat, include.lowest = TRUE, others = 0)
  aggregated_raster <- aggregate(classified_raster, fact = 10, na.rm = TRUE)
  resampled_raster <- resample(aggregated_raster, template_rast_5arcmin)
  return(resampled_raster)
}


result_list_SI_function_fi <- 
  lapply(threshold_fi, f_classify_and_aggregate_resample_fi)

r_SI_class_fraction_fi <- rast(result_list_SI_function_fi) %>% 
  crop_and_mask(., Finland_geom)
names(r_SI_class_fraction_fi) <- paste0("FracOfCell_ge", threshold_fi)

plot(r_SI_class_fraction_fi) 
# fraction >= 0 everywhere in Finland
# fraction >= 1 almost everywhere in Finland
# fraction >= 33 only in Southern Finland
# fraction >= 90 nowhere in Finland, i.e not that suitable land in Fin


# ------------------------- the same in ha
r_agrlandarea_inZabel_unrestricted_ha_perpix_fi <-
  r_SI_class_fraction_fi *
  cellSize(r_SI_class_fraction_fi[[1]], unit = "ha")  
names(r_agrlandarea_inZabel_unrestricted_ha_perpix_fi) <- paste0("Unrest_AgrLand_ha_whenSI_ge", threshold_fi) 
plot(r_agrlandarea_inZabel_unrestricted_ha_perpix_fi)
```

# Chunk 3

```{r}

f_limit_agrland_fi <- function(raster_layer) {
  na_mask <- is.na(raster_layer) | is.nan(raster_layer)
  limited_agrland <- ifel(test = raster_layer > r_fraction_gl_cl_total_fi, 
                          yes = r_fraction_gl_cl_total_fi,
                          no = raster_layer)
  limited_agrland[na_mask] <- NA
  return(limited_agrland)
}

r_fraction_agrland_max_based_on_SI_data_fi <- lapply(r_SI_class_fraction_fi, f_limit_agrland_fi) %>% 
  rast()
names(r_fraction_agrland_max_based_on_SI_data_fi) <- paste0("MaxFracOfCell_ge", threshold_fi) 
plot(r_fraction_agrland_max_based_on_SI_data_fi)



# sama df avulla
df_SI_class_fraction_fi <- as.data.frame(c(r_SI_class_fraction_fi, r_fraction_gl_cl_total_fi), xy = T, na.rm = F)

  # lisätään frac kun SI >= 0
df_SI_class_fraction_fi <- df_SI_class_fraction_fi %>% 
  mutate(AgrLandArea_restricted_frac_SI_0 = 
           ifelse(test = FracOfCell_ge0 > gl_cl_fraction_of_cell,
                  yes = gl_cl_fraction_of_cell,
                  no = FracOfCell_ge0)) %>% 
  mutate(AgrLandArea_restricted_frac_SI_0 = 
           ifelse(test = is.na(AgrLandArea_restricted_frac_SI_0) | is.nan(AgrLandArea_restricted_frac_SI_0),
                  yes = NA,
                  no = AgrLandArea_restricted_frac_SI_0))

  # lisätään frac kun SI >= 1
df_SI_class_fraction_fi <- df_SI_class_fraction_fi %>% 
  mutate(AgrLandArea_restricted_frac_SI_1 = 
           ifelse(test = FracOfCell_ge1 > gl_cl_fraction_of_cell,
                  yes = gl_cl_fraction_of_cell,
                  no = FracOfCell_ge1)) %>% 
  mutate(AgrLandArea_restricted_frac_SI_1 = 
           ifelse(test = is.na(AgrLandArea_restricted_frac_SI_1) | is.nan(AgrLandArea_restricted_frac_SI_1),
                  yes = NA,
                  no = AgrLandArea_restricted_frac_SI_1))


# !!! nyt rajoitettu ala ei voi olla suurempi kuin tämänhetkinen ala, mutta se voi olla pienempi

```

# Testaa globaaleja tuloksia

gl optimoitu proteiinisato saattaa toimia
cl optimoitu proteiinisato ei näytä toimivan

```{r}
# df_SI mukaan alkuperäinen dairy prot 31.9 ja optimoitu 43.8 kun SI on suurempi kuin 99
43.8/31.9 # 1.37 kertaa suurempi lehmäprotskusato
# samalla gl ala pienenee -974.5 eli ala kasvaa 974.5, mikä on
974.5/3253.4 # 0.3 eli 30% kasvu gl alaan (satokin noin 30% suurempi)
# sato näyttää olevan 1.37 eli 37% suurempi. Voi johtua siitä, että korkeampi NPP alueilla kuin keskiarvo alueilla jonne gl laajenee


# Kasvit
# Alkuperäien protsato 273.8 optimoitu proteiinisato 553.1 kun SI >= 99
553.1/273.8 # 2.02 --> ei voi olla mahdollista koska cl alan pitäisi laskea 974.5 eli noin 100% lähelle nollaa

```

