---
title: "Supplementary"
author: "Johannes Piipponen"
date: "`r Sys.Date()`"
output: html_document
---

# Raster showing abobeground fraction of the NPP
Based on Sun et al. https://link.springer.com/article/10.1007/s11427-020-1837-9



```{r}
#--------------------------- 5arcmin data created in E:input_data_processing.Rmd
data_all_but_animals_5arcmin <-
  here("Data", "Input", "art2_in_E",
       "data_all_but_animals_masked_where_pasture_every_year_2001_2020_5arcmin.tif") %>% 
  rast()

MAP <- data_all_but_animals_5arcmin$MAP
MAT <- data_all_but_animals_5arcmin$MAT

f_ANPP_fraction <-  (1 - (0.000000114*MAP^2 - 0.000307*MAP - 0.00665*MAT + 0.786))
  ## delete some negative values (somewhere in East Asia where it rains a lot)
ANPP_fraction <- f_ANPP_fraction
ANPP_fraction[ANPP_fraction < 0] <- NA ### !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! NOT NA ---> use 0 instead
plot(ANPP_fraction)

#writeRaster(ANPP_fraction, here("Data", "Supplementary", "fraction_of_NPP_aboveground.tif"))
global(ANPP_fraction, fun = "mean", na.rm = T) # 0.39

 ## average ANPP_fraction for Australia
ANPP_fraction %>% 
  crop_and_mask(adm10_simple_faoadded %>% filter(ADMIN == "Australia")) %>% 
  global(., fun = "mean", na.rm = T) # 0.47


# ------------------------------------------------------------ plot
pal_ANPP_fraction<-  scico(n = 7, palette = "hawaii", begin = 0.1, end = 0.8)


(plt_ANPP_fraction <- 
    create_index_map(r_index = ANPP_fraction,
                     tocrs = "ESRI:54030",
                     index_main_title = "Fraction of NPP allocated aboveground",
                     index_label = "",
                     colorpal = pal_ANPP_fraction,
                     breakvals = c(0, 0.10, 0.20, 0.30, 0.40, 0.50, 0.60, Inf),
                     breaknames = c("<0.1", "0.1-0.2","0.2-0.3",
                                    "0.3-0.4","0.4-0.5", "0.5-0.6", ">0.6"))) 
```


# Share of croplands and pasturelands in cell


```{r}
  ## for supplementary fig, convert zeros to NA for r_mcd_fractions

r_mcd_fraction_supplement <- c(r_mcd_fraction, r_mcd_fraction_allocated_to_cropland)
  ## remove NA for plotting
r_mcd_fraction_supplement[r_mcd_fraction_supplement == 0] <- NA

  ## combine fractions of crops in 5arcmin cells with fractions of pastures
r_fractions_crops_and_pastures <- 
  c(r_mcd_fraction_supplement,
    r_fraction_of_crops_in_cell, 
    r_fraction_of_crops_in_cell_pasturemask)

names(r_fractions_crops_and_pastures) <- c(
  "Share of pasturelands", "Share of pasturelands on croplands",
  "Share of cropland", "Share of cropland on pasturelands")




pal_shares <-  scico(n = 3, palette = "hawaii", begin = 0.1, end = 0.8)

(plt_shares_of_croplands_and_pasturelands <- 
    create_index_map(r_index = r_fractions_crops_and_pastures*100,
                     tocrs = "ESRI:54030",
                     index_main_title = "Shares of croplands and pasturelands in 5 arc-minutes cells",
                     index_label = "",
                     colorpal = pal_shares,
                     breakvals =  c(0,10,20,40,60,80, 100),
                     breaknames = c("0-10", "10-20","20-40","40-60","60-80", "80-100")) )





tmap_save(plt_shares_of_croplands_and_pasturelands, 
          here("Figures", "Supplementary",
               "Shares of croplands and pasturelands in 5 arc-minutes cells.png"),
          width = 180, height = 150, units = "mm")
```

# Plot kcal production from AGB and crops

```{r}
  ## this might work
pal_kcal<- scico(n = 10, palette = "hawaii",
                              direction = -1)

r_animal_kcal_nomask_and_croplands <- 
  c(r_animal_kcal_from_AGB_MM, r_animal_kcal_from_AGB_on_croplands_MM)

  ## kcal from AGB no mask
(plt_animal_kcal_nomask_and_croplands <- 
    create_index_map(r_index = r_animal_kcal_nomask_and_croplands,
                     tocrs = "ESRI:54030",
                     index_main_title = "Animal kcal production from AGB on pasturelands and on croplands (M kcal)",
                     index_label = "[million kcal per pixel]",
                     colorpal = pal_kcal,
                     breakvals = c(0,10,20,40,100, 200, 500, 1000, 5000, 10000, Inf),
                     breaknames = c("0-10", "10-20","20-40",
                                    "40-100","100-200", "200-500",
                                    "500-1000", "1000-5000", "5000-10000",
                                    ">10000"))  + 
    tm_facets(nrow = 4, ncol = 2) )  
 



tmap_save(plt_animal_kcal_nomask_and_croplands, 
          here("Figures", "Supplementary",
               "Animal kcal production from AGB(M kcal).pdf"),
          width = 180, height = 150, units = "mm")



#---------------------------------------------------------------------- crops
r_kcal_allcrops_sum_MM


(plt_crop_kcal_on_pasturelands <- 
    create_index_map(r_index = r_kcal_allcrops_sum_MM,
                     tocrs = "ESRI:54030",
                     index_main_title = "Crop kcal production on pasturelands (M kcal)",
                     index_label = "[million kcal per pixel]",
                     colorpal = pal_kcal,
                     breakvals = c(0,10,20,40,100, 200, 500, 1000, 5000, 10000, Inf),
                     breaknames = c("0-10", "10-20","20-40",
                                    "40-100","100-200", "200-500",
                                    "500-1000", "1000-5000", "5000-10000",
                                    ">10000")))


tmap_save(plt_crop_kcal_on_pasturelands, 
          here("Figures", "Supplementary",
               "Crop kcal production million.pdf"),
          width = 180, height = 150, units = "mm")


```


# Table S1 Name of crop species

```{r}
#------------------------------------------------------ selected crops to data frame
library(flextable)
df_appendix_21crops <- fbs_crops_wide %>% 
  group_by(Item, spamname) %>% 
  summarise(Average_fraction_of_protein = mean(protein_fraction, na.rm = T)) %>%
  mutate(across(where(is.numeric), ~ round(., 5))) %>% 
  flextable(., cwidth = 2)
df_appendix_21crops

save_as_image(df_appendix_21crops, path = here("Figures", "Supplementary", "selected_crops.png"))
save_as_docx(df_appendix_21crops, path = here("Figures", "Supplementary", "selected_crops.docx"))


```