---
title: "Test regressions"
author: "Johannes Piipponen"
date: "`r Sys.Date()`"
output: html_document
---

# Muutetaan dataframeksi regressiota varten

```{r}


df_protein_and_SI <- as.data.frame(r_protein_and_SI, xy = T)

  ## ainoastaan koordinaatit
df_xy <- df_protein_and_SI %>% 
  dplyr::select(x,y)

# tee regressio koko maailmalle -- myöhemmin pitää tunnistaa mitkä kuuluvat millekin maalle
df_regression <- df_protein_and_SI %>% 
  dplyr::select(-c(x,y)) %>% 
  filter(overall_suitability > 0,
         !is.na(crop_protein_kg_ha),
         crop_protein_kg_ha < 826.4333 )

hist(df_regression$crop_protein_kg_ha)
hist(df_regression$overall_suitability)

ggplot(data = tail(df_regression, 1e4),
       aes(x = overall_suitability, y =crop_protein_kg_ha)) +
  geom_point() # ei tolkkua maailman tasolla



mymodel <- 
  lm(crop_protein_kg_ha ~ overall_suitability, 
     data = df_regression)

summary(mymodel) #188 + 1.05 käy järkeen

  ## kokeillaan. Jos SI on 75
mymodel_predict <- 188 + 1.05*75 # 266.75 kg of protein from ha
  ## jos taas etsitään alueet joilla SI > 75, paljonko proteiinisato siellä?
SI_more_than75 <- SI_5arcmin
SI_more_than75[SI_more_than75 <75] <- NA # tää valitsee alueet joilla SI > 75 --- pitäisi valita ne joilla nimenomaan 75
plot(SI_more_than75)

r_protein_yields_where_SIover75 <- mask(r_prot_allcrops_sum_kg_ha, SI_more_than75)
summary(r_protein_yields_where_SIover75) # median 274 eli noin 3% heitto





# kokeillaan jos SI 75 --- regression mukaan protskua silloin 283.25
df_regression %>% 
  filter(overall_suitability == 75) %>% 
  dplyr::select(crop_protein_kg_ha) %>% 
  summary() # median 305, mean 296


# kokeillaan jos SI 10 --- regression mukaan protskua silloin 226.7
df_regression %>% 
  filter(overall_suitability == 10) %>% 
  dplyr::select(crop_protein_kg_ha) %>% 
  summary() # median 84, mean 213


df_regression %>% 
  filter(overall_suitability == 10) %>% 
  dplyr::pull(crop_protein_kg_ha) %>% 
  hist(.) # aika isoa heiluntaa. Pitää ehkä valita 5% - 95% väli ja tehdä joka maalle. Sitten ehkä parempia tuloksia
```


# regressiokokeilu Suomi

```{r}
r_protein_and_SI_Fin <- crop_and_mask(r_protein_and_SI, Finland_geom)
df_protein_and_SI_Fin <- as.data.frame(r_protein_and_SI_Fin, xy = T)
summary(df_protein_and_SI_Fin) # remove outliers in crop protein production

quantile(df_protein_and_SI_Fin$crop_protein_kg_ha, probs = c(0.05, 0.95), na.rm = T) # 114 - 1242

df_protein_and_SI_Fin_regression <- df_protein_and_SI_Fin %>% 
  filter(crop_protein_kg_ha < 1242) %>% 
  dplyr::select(-c(x,y))

# plottaa
plot(df_protein_and_SI_Fin_regression$overall_suitability,
     df_protein_and_SI_Fin_regression$crop_protein_kg_ha)




mymod_fin <- lm(crop_protein_kg_ha ~ overall_suitability,
                data = df_protein_and_SI_Fin_regression)
summary(mymod_fin) # 293.0091      + 3.8*SI


## testaa 10
# kokeillaan jos SI 10 --- regression mukaan protskua silloin  236 -- ei edes lähellä
# df_protein_and_SI_Fin_regression %>% 
#   filter(overall_suitability == 10) %>% 
#   dplyr::pull(crop_protein_kg_ha) %>% 
#   summary() # median 154, mean 171
# 
# df_protein_and_SI_Fin_regression %>% 
#   filter(overall_suitability == 10) %>% 
#   dplyr::pull(crop_protein_kg_ha) # vain 5 arvoa -- tämä siksi koska overall_suitability aggregoitu, eikä siksi ole tasan 10
# 
# df_protein_and_SI_Fin_regression %>% 
#   filter(overall_suitability < 10) %>% 
#   dplyr::pull(crop_protein_kg_ha) %>% 
#   summary() # med 222, mean 227 -- aika lähellä ollaan!

# tai
df_protein_and_SI_Fin_regression %>% 
  filter(round(overall_suitability, digits = 0) == 10) %>% 
  dplyr::pull(crop_protein_kg_ha) %>% 
  summary() # med 270 mean 311 kun olemassaolevasta datasta valitaan havainnot jolloin si = 10
  ## -- aika lähellä ollaan ennustetta 331!


## testaa 30 -- regression mukaan 407
df_protein_and_SI_Fin_regression %>% 
  filter(round(overall_suitability, digits = 0) == 30) %>% 
  dplyr::pull(crop_protein_kg_ha) %>% 
  summary() # med 417 mean 396
```



# Tee regressio jokaiselle eri maalle



```{r}

# Wrapper function for linear regression
fit_lm_possibly <- function(data) {
  lm(crop_protein_kg_ha ~ overall_suitability, data = data) %>% 
    broom::tidy() %>%
    dplyr::select(term, estimate, p.value)
}

# Safe version of the linear regression function
fit_lm_safe <- purrr::possibly(fit_lm_possibly, otherwise = tibble::tibble(
  term = c("(Intercept)", "overall_suitability"),
  estimate = c(NA, NA),
  p.value = c(NA, NA)
))


# Function to perform linear regression analysis for a specific country
f_regression_for_a_country <- function(countrytoselect) {
  
  # Find a polygon for the selected country
  country_polygon <- adm10_simple_faoadded  %>% filter(ADMIN == countrytoselect) %>% 
    dplyr::select(ADMIN) |> as("Spatial") |>   vect()
  
  # Crop and mask raster for the selected country
  r_protein_and_SI_country <- crop_and_mask(r_protein_and_SI, country_polygon)
  
  # Convert raster to data frame
  df_protein_and_SI_country <- as.data.frame(r_protein_and_SI_country, xy = T)
  
  # Calculate the 95th percentile of protein yield values
  outlier_level <- quantile(df_protein_and_SI_country$crop_protein_kg_ha,
                            probs =  0.95, na.rm = T)
  
  # Filter out the top 5% of protein yield values (potential outliers)
  df_protein_and_SI_country_regression <- df_protein_and_SI_country %>% 
    filter(crop_protein_kg_ha < outlier_level) %>% 
    dplyr::select(-c(x,y))
  
  # Perform linear regression using the safe version of the function
  mymodel_results_country <- fit_lm_safe(df_protein_and_SI_country_regression)
  
  # Add country name to the results and reshape data frame
  mymodel_results_country <- mymodel_results_country %>%
    mutate(country = countrytoselect) %>%
    pivot_wider(names_from = term, values_from = c(estimate, p.value))
  
  return(mymodel_results_country)
}

f_regression_for_a_country("Finland")



regression_results_bycountry <- 
  map_df(adm10_simple_faoadded$ADMIN %>% unique(), 
                f_regression_for_a_country) %>% 
  rename(estimate_intercept = "estimate_(Intercept)") %>% 
  dplyr::select(-"p.value_(Intercept)")


# check
regression_results_bycountry$estimate_intercept %>% summary()
regression_results_bycountry %>% 
  filter(p.value_overall_suitability < 0.05) %>% 
  dplyr::select(estimate_intercept) %>% summary()

```




# Olisiko joku toinen malli parempi? Jos esim poistettu bottom ja top 5% datasta?

```{r}
# Filtteröidään data niin, että outlierit poistettu. Poistetaan myös x ja y
country_df_filtered_list_SIover0 <- map2(country_df_list, outlier_level_list, ~.x %>% 
                                   filter(crop_protein_kg_ha <= .y, overall_suitability > 0) %>% 
                                   dplyr::select(-c(x, y)))
country_df_filtered_list_SIover0[[53]] # tässä data regressiota varten


model_list_SIover0 <- map(country_df_filtered_list_SIover0, fit_lm_safe)
model_list_SIover0[[53]] # suomen tulos, mutta kahdella rivillä, olisi parempi jos kaikki olisivat yhdessä rivissä


# yhdistetään nested country_df_filtered_list polygonien kanssa
all_countries_cleaned_SIover0 <- adm10_simple_faoadded %>% 
  mutate(country_df_filtered_list_SIover0 = country_df_filtered_list_SIover0,
         model_list_SIover0 = model_list_SIover0)  %>% 
  dplyr::select(ADMIN, REGION_UN, geom, model_list_SIover0) %>%
  mutate(model_list_SIover0 = map(model_list_SIover0, ~ as_tibble(.x))) %>%
  unnest(cols = model_list_SIover0)



View(all_countries_cleaned_SIover0)




# ----------------------------------------------------------- comp 3
country_df_filtered_list_SIover1 <- map2(country_df_list, outlier_level_list, ~.x %>% 
                                   filter(crop_protein_kg_ha <= .y, overall_suitability > 1) %>% 
                                   dplyr::select(-c(x, y)))
country_df_filtered_list_SIover1[[53]] # tässä data regressiota varten

model_list_SIover1 <- map(country_df_filtered_list_SIover1, fit_lm_safe)
model_list_SIover1[[53]] # suomen tulos, mutta kahdella rivillä, olisi parempi jos kaikki olisivat yhdessä rivissä


# yhdistetään nested country_df_filtered_list polygonien kanssa
all_countries_cleaned_SIover1 <- adm10_simple_faoadded %>% 
  mutate(country_df_filtered_list_SIover1 = country_df_filtered_list_SIover1,
         model_list_SIover1 = model_list_SIover1)  %>% 
  dplyr::select(ADMIN, REGION_UN, geom, model_list_SIover1) %>%
  mutate(model_list_SIover1 = map(model_list_SIover1, ~ as_tibble(.x))) %>%
  unnest(cols = model_list_SIover1)
```


# Compare models

```{r}
all_countries_cleaned
all_countries_cleaned_SIover0
all_countries_cleaned_SIover1

all_countries_cleaned %>% filter(pvalue_suitability < 0.05) %>% dplyr::select(r.squared) %>%  summary() # med 0.04, mean 0.08
all_countries_cleaned_SIover0 %>% filter(pvalue_suitability < 0.05) %>% dplyr::select(r.squared) %>%  summary() # med 0.04, mean 0.08
all_countries_cleaned_SIover1 %>% filter(pvalue_suitability < 0.05) %>% dplyr::select(r.squared) %>%  summary()

# good fir
filter(all_countries_cleaned, r.squared > 0.25) %>% dim() # 15
filter(all_countries_cleaned_SIover0, r.squared > 0.25) %>% dim() # 13
filter(all_countries_cleaned_SIover1, r.squared > 0.25) %>% dim() # 14

```



# Explore model (the selected one) quality

```{r}
# Filter out contries with low p value
pval_low_countries <- all_countries_cleaned %>% 
  filter(pvalue_suitability >= 0.05) ## 55 countries --> map these! What do we do in these countries?


# Plot the R-squared values for each continent
all_countries_cleaned %>%
  ggplot(aes(REGION_UN, r.squared)) +
  geom_jitter(width = 0.5)+
  theme_classic()

# same but only for significant countries
pval_low_countries %>%
  ggplot(aes(REGION_UN, r.squared)) +
  geom_jitter(width = 0.5)+
  theme_classic()




# Filter countries with low R-squared values (e.g., less than 0.10)
good_fit <- filter(all_countries_cleaned, r.squared > 0.25) # 15 countries




all_countries_cleaned %>% 
  filter(pvalue_suitability < 0.05) %>% 
  dplyr::select(r.squared) %>% 
  summary() # med 0.04, mean 0.08

summary(pval_low_countries$r.squared) # median r squared 1/10 compared to all countries





# Add residuals
by_country <- all_countries %>% 
  mutate(
    resids = map2(country_df_filtered_list, model_list, add_residuals)
  )
by_country





```

